import type { Product } from "./types"

export const products: Product[] = [
  {
    id: "1",
    name: "Premium Night Pants",
    category: "night-pants",
    price: 2499,
    images: [
      "/premium-black-night-pants-soft-fabric.jpg",
      "/black-night-pants-front-view.jpg",
      "/black-night-pants-side-view.jpg",
      "/black-night-pants-back-view.jpg",
    ], // Added multiple images
    description:
      "Ultra-comfortable premium night pants made from breathable cotton blend fabric. Perfect for a good night's sleep.",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Black", "Navy", "Grey", "Maroon"],
    rating: 4.8,
  },
  {
    id: "2",
    name: "Classic T-Shirt",
    category: "t-shirts",
    price: 799,
    images: [
      "/classic-white-t-shirt-cotton.jpg",
      "/white-t-shirt-front.png",
      "/white-t-shirt-side.png",
      "/white-t-shirt-back-view.png",
    ],
    description: "Timeless classic t-shirt made from 100% organic cotton. Comfortable and versatile for everyday wear.",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    colors: ["White", "Black", "Blue", "Red", "Green"],
    rating: 4.6,
  },
  {
    id: "3",
    name: "Winter Jacket",
    category: "jackets",
    price: 5999,
    images: [
      "/premium-winter-jacket-black-leather.jpg",
      "/black-winter-jacket-front.jpg",
      "/black-winter-jacket-side.jpg",
      "/black-winter-jacket-back.jpg",
    ],
    description:
      "Stylish winter jacket with premium quality material. Provides warmth and elegance for the colder months.",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Black", "Brown", "Navy"],
    rating: 4.9,
  },
  {
    id: "4",
    name: "Track Pants",
    category: "track-pants",
    price: 1999,
    images: [
      "/athletic-track-pants-black.jpg",
      "/athletic-track-pants-front.jpg",
      "/athletic-track-pants-side.jpg",
      "/athletic-track-pants-back.jpg",
    ],
    description:
      "Comfortable track pants designed for active lifestyle. Made from breathable synthetic fabric with elastic waistband.",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Black", "Grey", "Navy", "Maroon"],
    rating: 4.7,
  },
  {
    id: "5",
    name: "Cozy Hoodie",
    category: "hoodies",
    price: 2299,
    images: [
      "/cozy-hoodie-grey-casual-wear.jpg",
      "/grey-hoodie-front-view.jpg",
      "/grey-hoodie-side-view.jpg",
      "/grey-hoodie-back-view.jpg",
    ],
    description: "Perfect hoodie for cozy days. Soft fleece lining and spacious pockets make it ideal for any season.",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    colors: ["Grey", "Black", "Blue", "White", "Green"],
    rating: 4.8,
  },
  {
    id: "6",
    name: "Summer Shorts",
    category: "shorts",
    price: 999,
    images: [
      "/summer-shorts-athletic-blue.jpg",
      "/blue-summer-shorts-front.jpg",
      "/blue-summer-shorts-side.jpg",
      "/blue-summer-shorts-back.jpg",
    ],
    description: "Lightweight shorts perfect for summer. Quick-dry fabric and comfortable fit for any activity.",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Blue", "Black", "Grey", "Red", "White"],
    rating: 4.5,
  },
  {
    id: "7",
    name: "Sleek Black T-Shirt",
    category: "t-shirts",
    price: 899,
    images: [
      "/sleek-black-t-shirt-premium.jpg",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
    description: "Premium quality black t-shirt with perfect fit. Ideal for casual and semi-formal occasions.",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    colors: ["Black"],
    rating: 4.7,
  },
  {
    id: "8",
    name: "Formal Jacket",
    category: "jackets",
    price: 7999,
    images: [
      "/formal-blazer-jacket-navy.jpg",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
    description: "Elegant formal jacket perfect for professional settings. Made from premium wool blend fabric.",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Navy", "Black", "Grey"],
    rating: 4.9,
  },
  {
    id: "9",
    name: "Cotton Blend Shorts",
    category: "shorts",
    price: 1199,
    images: [
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
    description: "Versatile cotton blend shorts perfect for casual wear. Comfortable waistband and durable fabric.",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Khaki", "Navy", "Black", "Olive"],
    rating: 4.6,
  },
  {
    id: "10",
    name: "Sports Hoodie",
    category: "hoodies",
    price: 2799,
    images: [
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
    description: "Premium sports hoodie with moisture-wicking technology. Perfect for workouts and casual wear.",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    colors: ["Black", "Grey", "Navy", "White"],
    rating: 4.8,
  },
  {
    id: "11",
    name: "Comfort Night Wear",
    category: "night-pants",
    price: 1899,
    images: [
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
    description:
      "Ultra-soft comfortable night wear designed for maximum comfort. Breathable fabric for all-night comfort.",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Light Blue", "Cream", "Grey", "Navy"],
    rating: 4.7,
  },
  {
    id: "12",
    name: "Premium Track Suit",
    category: "track-pants",
    price: 3499,
    images: [
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
    description: "Complete premium track suit for workouts and casual wear. Stylish and comfortable design.",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Black", "Grey", "Navy", "White"],
    rating: 4.9,
  },
]
